[theme]
primaryColor = "#1f77d2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
runOnSave = true
port = 8501
headless = true
